################################# Default configuration ###################
# provide your domain here
baseURL = "https://help.pricewell.com/"
baseurl = "https://help.pricewell.com/"
# theme
theme = "pricewell-docs"
# site title
title = "PriceWell Help Center"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true

[algolia]
index = "pricewell-docs"
key = "***REMOVED***"
appID = "19UQLY9O07"


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = "images/pricewell-logo.png"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = "images/pricewell-logo-white.png"
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "PriceWell"
image = "images/pricewell-logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#1d3557"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "roboto" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "mailto:support@pricewell.io" # contact form works with : https://formspree.io



################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright &copy; 2022 Codefish Apps Ltd"

# banner
[Languages.en.params.banner]
title = "PriceWell Help Center"
subtitle = "Explore our guides and examples to integrate PriceWell"
bg_image = ""
placeholder = "Search for answers"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "We are here to help you. No question is too small for our customer support team of <u>Stripe</u> and <u>No-Code</u> experts."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "Contact Support"
link = "mailto:support@pricewell.io"
